name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Start Minikube
      uses: medyagh/setup-minikube@latest
    
    - name: Build Docker Image
      run: |
        eval $(minikube docker-env)
        docker build -t task-manager-api:${{ github.sha }} .
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/mongodb-deployment.yaml
        kubectl apply -f kubernetes/task-manager-deployment.yaml
    
    - name: Wait for Deployment
      run: |
        kubectl wait --for=condition=ready pod -l app=mongodb --timeout=300s
        kubectl wait --for=condition=ready pod -l app=task-manager --timeout=300s
    
    - name: Get Service URL
      run: |
        kubectl get services
        minikube service task-manager-service --url
    
    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get deployments
        kubectl get services